In [1]:
#2a
def constant(n,m,c):
    list = []
    for row in range(m):
        list2 = []
        for col in range(n):
            list2.append(float(c))
        list.append(list2)
    return list


In [2]:
#Test Solution
output = constant(2,3,4)
print output

[[4.0, 4.0], [4.0, 4.0], [4.0, 4.0]]


In [3]:
#2b(i)
def zeros(n,m):
    list = []
    for i in range(m):
        list.append([])
        for j in range(n):
            list[-1].append(float(0))
    return list

In [4]:
#Test Solution
output = zeros(2,3)
print output

[[0.0, 0.0], [0.0, 0.0], [0.0, 0.0]]


In [44]:
#2b(ii)
def ones(n,m):
    list = []
    for i in range(m):
        list.append([])
        for j in range(n):
            list[-1].append(float(1))
    return list

In [46]:
#Test Solution
output = ones(2,3)
print output

[[1.0, 1.0], [1.0, 1.0], [1.0, 1.0]]


In [77]:
#2c
def eye(n):
    iden=[[0 for x in range(n)] for y in range(n)]
    for i in range(0,n):
        iden[i][i] = 1
    return iden

In [78]:
#Test Solution
output = eye(5)
print output

[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]


In [3]:
#3a
def shape(M):
    r = len(M)
    c = len(M[0])
    x = (r,c)
    for i in M:
        if len(i)!=c:
            return False
        else:
            c=len(i)
    return x


In [4]:
#Test Solution
output = shape([[1, 2],[3, 4],[5, 6]])
print output

(3, 2)


In [3]:
#3b(i)
def row(M,n):
    out = []
    for i in M:
        r = i[n]
        out.append(r)
    return out

In [4]:
#Test Solution
output = row([[1, 2],[3, 4],[5, 6]],1)
print output

[2, 4, 6]


In [79]:
#3b(ii)
def column(M,n):
    c = M[n]
    return c

In [80]:
#Test Solution
output = column([[1, 2, 5],[3, 4, 6],[5, 6, 8]],0)
print output

[1, 2, 5]


In [41]:
#3c
def block(M,n_0,n_1,m_0,m_1):
    rows = 
    cols = 
    return rows,cols
   

In [42]:
#Test Solution
output = block([[1, 2, 5],[3, 4, 6],[10, 6, 8]],0,2,0,1)
print output

(array([0, 2]), array([0, 1]))


In [5]:
#4a
def transpose(M):
    t = []
    i = 0
    while i<len(M):
        j = 0
        cv = []
        while j < len(M):
            cv.append(M[j][i])
            j = j + 1
        t.append(cv)
        i = i + 1
    return t

In [6]:
#Test Solution
output = transpose([[1, 2, 5],[3, 4, 6],[10, 6, 8]])
print output

[[1, 3, 10], [2, 4, 6], [5, 6, 8]]


In [7]:
#4b
def scalarmul(M,c):
    result = []
    i=0
    while i<len(M):
        j=0
        list_within = []
        while j<len(M):
            sc = c*j
            list_within.append(sc)
            j=j+1
        result.append(list_within)
        i=i+1
    return result

In [8]:
#Test Solution
output = scalarmul([[1, 2, 5],[3, 4, 6],[10, 6, 8]],2)
print output

[[0, 2, 4], [0, 2, 4], [0, 2, 4]]


In [9]:
#4c
def add(M,N):
    ad = []
    for i in range(len(M)):    
        for j in range(len(M[0])): 
            ad[i][j] = M[i][j] + N[i][j] 
        ad.append(ad[i][j])
    #if and else statement for Addition of matrices without same size
        x_r = len(M)
        x_c = len(M[0])
        x_r_c = (x_r,x_c)
        y_r = len(N)
        y_c = len(N[0])
        y_r_c = (y_r,y_c)
        if x_r_c != y_r_c:
            return False
        else:
            x_r_c = y_r_c
        return ad 
    
    

In [10]:
#Test Solution
output = add([[1, 2, 5],[3, 4, 6],[10, 6, 8]],[[10, 2, 5],[3, 4, 6],[10, 6, 8]])
print output

IndexError: list index out of range

In [45]:
#4d
import numpy as np
def sub(M,N):
    def scalarmul(N,c):
        scale = c*np.array(N)
        return scale
    def add(M,N):
        x = np.array(M)
        y = np.array(N)
        ad = x+y
    return ad
    

In [46]:
#Test Solution
N = scalarmul([[1, 2, 5],[3,4,6],[10, 6, 8]],-1)
print N
M_minus_N = add([[10, 2, 5],[3, 4, 6],[10, 6, 8]],N)
print M_minus_N

[[ -1  -2  -5]
 [ -3  -4  -6]
 [-10  -6  -8]]
[[9 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
#4e
def elementmult(M,N):
    a = []
    
    return a


In [49]:
#4f
def matmult(M,N): 
    def zeros(n,m):
        list = []
        for i in range(m):
            list.append([])
            for j in range(n):
                list[-1].append(float(0))
        return list

    def matrix_multiply(M,N):
        mM = len(M)
        nM = len(M[0])

        mN = len(N)
        nN = len(N[0])

        if nM != mN:
            print('Number of M columns must equal number of N rows.')

        Cons = zeros(n,m)
        for i in range(mM):
            for j in range(nN):
                total = 0
                for w in range(nM):
                    total += A[i][w] * B[w][j]
                Cons[i][j] = total

        return Cons



In [50]:
M = [[10, 2, 5],[3, 4, 6],[10, 6, 8]]
N = [[2, 2, 5],[3, 4, 8],[10, 6, 8]]
output = matmult(M,N)
print output

None


In [5]:
#In order to find inverse M has to satisfy certain conditions
# 1. It has to be a square matrix 
# 2. The determinant canot equal 0
def inv(M)
    def squarematrix(M):
        numrows = len(M)
        numcols = len(M[0])
        if numrows==numcols:
            return M
        else:
            print("Not a square matrix. Inverse does not exist")
    def determinant(M):
        if len(M)==2 and len(M[0])==2: #2x2 square matrix case
            det = (M[0][0]*M[1][1])-(M[0][1]*M[1][0])
            if det == 0:
                print("Determinant is 0. Inverse does not exist")
            else:
                return [[m[1][1]/det, -1*m[0][1]/det],
                [-1*m[1][0]/det, m[0][0]/det]]
#case for non 2x2 matrix 
#Two options for this case
# 1. Reduced row form
# 2. Determinant method: This is the method I will be using 
    # a. Find Determinant
    # b. Tranpose matrix
    # c. Find determinant of minor matrices
    # d. Create matrix of co-factors
    # e. Divide each term of the adjugate matrix by the determinant
    def determinant1(M):
        if len(M) or lenM[0] !=2:
            
    def transpose1(M):
        t = []
        i = 0
        while i<len(M):
            j = 0
            cv = []
            while j < len(M):
                cv.append(M[j][i])
                j = j + 1
            t.append(cv)
            i = i + 1
        return t
    def minorMatrix(M,i.j):
        for row in (M[:i]+M[i+1:])
        return  return [row[:j] + row[j+1:]



IndentationError: expected an indented block (<ipython-input-5-b271069cb47c>, line 31)

In [34]:
output = inv([[3,2],[4,5]])
print output

None
